name: CyanogenMod Compiling CI

on:
  workflow_dispatch:

jobs:
  build:
    name: TWRP Build CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Installing JDK 7 + Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install zip gcc-multilib g++-multilib \
          libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
          libgl1-mesa-dev libxml2-utils xsltproc schedtool axel
        mkdir ~/.jdk_7
        cd ~/.jdk_7
        axel -q -n $(nproc --all) https://repo.huaweicloud.com/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin
        chmod +x jdk-6u45-linux-x64.bin
        ./jdk-6u45-linux-x64.bin
        sudo ln -f -s /usr/bin/python2.7 /usr/bin/python
    - name: Syncing CyanogenMod sources
      run: |
        mkdir ~/TWRP
        cd ~/TWRP
        mkdir ~/.bin
        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        python3 ~/.bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-4.4-deprecated
        python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
    - name: Syncing androidarmv6 sources
      run: |
        git clone https://github.com/unlegacy-devices/android_device_samsung_totoro -b cm-11.0 ~/TWRP/device/samsung/totoro
        git clone https://github.com/androidarmv6/android_device_samsung_bcm21553-common -b cm-11.0 ~/TWRP/device/samsung/bcm21553-common
        git clone https://github.com/androidarmv6/android_vendor_samsung -b cm-11.0 ~/TWRP/vendor/samsung
        git clone https://github.com/androidarmv6/android_kernel_samsung_bcm21553-common -b cm-11.0 ~/TWRP/kernel/samsung/bcm21553-common
        git clone https://github.com/androidarmv6/android_hardware_broadcom_brcm_usrlib -b cm-11.0 ~/TWRP/hardware/broadcom/brcm_usrlib
    - name: Building TWRP
      run: |
        OLDPATH=$PATH
        OLDJAVAHOME=$JAVA_HOME
        export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
        export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
        cd ~/TWRP
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        lunch cm_totoro-eng
        make -j$(nproc --all) recoveryimage
        export PATH=$OLDPATH
        export JAVA_HOME=$OLDJAVAHOME
    - name: Uploading TWRP builds
      uses: actions/upload-artifact@v2
      with:
        name: twrp
        path: /home/runner/TWRP/out/target/product/totoro/recovery.*
